name: Build, Test, and Deploy App

on:
  push:
    branches:
      - master
      - production
  pull_request:
    branches:
      - master
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.3  # Use the latest version of setup-uv
        with:
          python-version: 3.13  # Specify the Python version your project uses

      - name: Install dependencies
        run: uv sync --frozen

      #- name: Build project (optional, if your project is a package)
      #  run: uv build

      - name: Run tests
        run: uv run pytest # Replace 'pytest' with your chosen test runner command

  # QA deployment job
  deploy-to-qa:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
#    permissions:
#      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/farnswj1/example-app-1/app:staging

      - name: Deploy to staging/QA
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_STAGING_HOST }}
          username: ${{ secrets.SSH_STAGING_USERNAME }}
          key: ${{ secrets.SSH_STAGING_PRIVATE_KEY }}
          script: |
            cd ~/qa
            docker pull ghcr.io/farnswj1/example-app-1/app:staging
            docker compose up -d app
#
#  # Production deployment job
#  deploy-to-production:
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/production'
#    needs: build-and-test
#    permissions:
#      packages: write
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Pull Docker image
#        run: docker pull ghcr.io/farnswj1/example-app-1/app:staging
#
#      - name: Tag Docker image for production
#        run: docker tag ghcr.io/farnswj1/example-app-1/app:staging ghcr.io/farnswj1/example-app-1/app:latest
#
#      - name: Push Docker image to production
#        run: docker push ghcr.io/farnswj1/example-app-1/app:latest
#